version: '3'
services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    # labels:
    #   - "traefik.http.routers.s3.rule=Host(`s3.test.ctg.lu`)"
    #   - "traefik.http.routers.s3.entrypoints=web,websecure"
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.s3.tls=true"
    #   - "traefik.http.services.s3.loadbalancer.server.port=9001"
    #   - "traefik.http.routers.s3.tls.certresolver=myresolver"
    volumes:
      - ./other_services/storage/minio:/data 
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server /data  --console-address ":9001"
    networks: 
      - proxy

  dev_env:
    build: .
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks: 
      - proxy

networks:
  proxy:
    external: True